Repository LiteLDev/LeviLamina, pull requests merged in 2022-12, with the labels that each got.

#927 修复部分不标准参数
  ScriptEngine/src/api/EventAPI.cpp
Labels: type: enhancement, module: LLSE

#933 Add more parameters for LLSE PlayerEffectChangedEvent
  LiteLoader/src/llapi/mc/PlayerAPI.cpp
  ScriptEngine/src/api/EventAPI.cpp
Labels: type: enhancement, module: LLSE

#936 Make C++/CLI project can pass build
  LiteLoader/include/llapi/Global.h
Labels: type: enhancement, module: .NET

#941 Fix some bugs
  LiteLoader/include/llapi/PlayerInfoAPI.h
  LiteLoader/include/llapi/mc/Player.hpp
  LiteLoader/src/llapi/PlayerInfoAPI.cpp
  LiteLoader/src/llapi/mc/PlayerAPI.cpp
  ScriptEngine/src/api/DataAPI.cpp
  ScriptEngine/src/api/DataAPI.h
  ScriptEngine/src/api/PlayerAPI.cpp
Labels: type: enhancement, module: script engine, module: LiteLoader, priority: normal

#955 Fix warnings in workflows
  .github/workflows/cmake_pr.yml
  .github/workflows/cmake_repo.yml
  .github/workflows/publish_release.yml
Labels: type: enhancement, about: CI

#954 Fix generation fails when the project directory contains spaces
  LiteLoader/CMakeLists.txt
Labels: type: bug

#948 Refactor checkRunningBDS()
  LiteLoader/src/liteloader/LiteLoader.cpp
Labels: type: bug, module: LiteLoader

#970 Fix #969
  LiteLoader/include/llapi/I18nAPI.h
  LiteLoader/src/llapi/I18nAPI.cpp
Labels: type: enhancement, module: LiteLoader
