Repository LiteLDev/LeviLamina, pull requests merged in 2022-08, with the labels that each got.

#572 Update Slider & CustomForm
  LiteLoader/Header/FormUI.h
  LiteLoader/Kernel/FormPacketHelper.cpp
  LiteLoader/Kernel/FormUI.cpp
Labels: pr: incompatible

#723 LLSE: Some PlayerAPI parameters and `setFire`
  ScriptEngine/API/PlayerAPI.cpp
  ScriptEngine/API/PlayerAPI.h
  docs/en_US/Development/GameAPI/Player.md
  docs/zh_CN/Development/GameAPI/Player.md
Labels: documentation, enhancement

#724 Fix global namespace pollution
  LiteLoader/Header/EventAPI.h
  LiteLoader/Header/KVDBAPI.h
  LiteLoader/Header/LoggerAPI.h
  LiteLoader/Header/SendPacketAPI.h
  LiteLoader/Header/Utils/Bstream.h
  LiteLoader/Header/Utils/DbgHelper.h
  LiteLoader/Header/Utils/Hash.h
  LiteLoader/Header/Utils/ViewHelper.h
  LiteLoader/Kernel/KVDBAPI.cpp
Labels: enhancement

#726 LLSE: New methods and properties in LlAPI
  ScriptEngine/API/LlAPI.cpp
  ScriptEngine/API/LlAPI.h
  docs/en_US/Development/GameAPI/Basic.md
  docs/en_US/Development/ScriptAPI/Ll.md
  docs/zh_CN/Development/ScriptAPI/Ll.md
Labels: documentation, enhancement, module: LLSE

#739 Add more properties in PlayerAPI and EntityAPI (LLSE)
  ScriptEngine/API/EntityAPI.cpp
  ScriptEngine/API/EntityAPI.h
  ScriptEngine/API/PlayerAPI.cpp
  ScriptEngine/API/PlayerAPI.h
  docs/en_US/Development/GameAPI/Entity.md
  docs/en_US/Development/GameAPI/Player.md
  docs/zh_CN/Development/GameAPI/Entity.md
  docs/zh_CN/Development/GameAPI/Player.md
Labels: enhancement, module: LLSE

#741 Move ParticleAPI to dll
  LiteLoader/Header/ParticleAPI.h
  LiteLoader/Kernel/EventAPI.cpp
  LiteLoader/Kernel/ParticleAPI.cpp
  LiteLoader/LiteLoader.vcxproj
  LiteLoader/LiteLoader.vcxproj.filters
  LiteLoader/Main/LiteLoader.cpp
  ScriptEngine/API/ParticleAPI.cpp
  ScriptEngine/API/ParticleAPI.h
Labels: enhancement, module: LLSE, module: Core

#736 Add I18nAPI for LLSE
  LiteLoader/Header/I18nAPI.h
  ScriptEngine/API/APIHelp.h
  ScriptEngine/API/InternationalAPI.cpp
  ScriptEngine/API/InternationalAPI.h
  ScriptEngine/Engine/EngineOwnData.h
  ScriptEngine/Main/BindAPIs.cpp
  docs/en_US/Development/ScriptAPI/i18n.md
  docs/zh_CN/Development/ScriptAPI/i18n.md
Labels: enhancement, module: LLSE
