Repository LiteLDev/LeviLamina, pull requests merged in 2022-09, with the labels that each got.

#752 Add enums in Types.hpp
  LiteLoader/Header/MC/Types.hpp
  ScriptEngine/API/PlayerAPI.cpp
Labels: enhancement, module: Core

#763 Add some docs
  LiteLoader/Header/EventAPI.h
  LiteLoader/Header/MC/ItemStack.hpp
  LiteLoader/Header/MC/Player.hpp
Labels: documentation

#746 Add PlayerUseBucket Event
  LiteLoader/Header/EventAPI.h
  LiteLoader/Kernel/EventAPI.cpp
  ScriptEngine/API/EventAPI.cpp
Labels: enhancement, module: LLSE, module: Core

#769 Update ItemAPI for LLSE
  ScriptEngine/API/ItemAPI.cpp
  ScriptEngine/API/ItemAPI.h
Labels: type: enhancement, module: LLSE

#774 Add docs for the Level class
  LiteLoader/Header/DB/Any.h
  LiteLoader/Header/DB/ConnParams.h
  LiteLoader/Header/DB/Impl/MySQL/Stmt.h
  LiteLoader/Header/DB/Pointer.h
  LiteLoader/Header/DB/Row.h
  LiteLoader/Header/DB/Stmt.h
  LiteLoader/Header/I18nAPI.h
  LiteLoader/Header/MC/Level.hpp
  LiteLoader/Header/MC/Player.hpp
  LiteLoader/Header/PERM/Foundation.hpp
  LiteLoader/Header/PERM/Permission.hpp
  LiteLoader/Header/PERM/Role.hpp
  LiteLoader/Header/PermissionAPI.h
  LiteLoader/Header/PlayerInfoAPI.h
Labels: type: documentation, type: enhancement, module: Core

#831 Update Beta
  .github/ISSUE_TEMPLATE/bug_report_en.yml
  .github/ISSUE_TEMPLATE/bug_report_zh.yml
  .github/workflows/cmake-self-hosted.yml
  .github/workflows/cmake.yml
  .github/workflows/publish_release.yml
  CHANGELOG.md
  LiteLoader/include/liteloader/Config.h
  LiteLoader/include/liteloader/Version.h
  LiteLoader/include/llapi/EventAPI.h
  LiteLoader/include/llapi/mc/Player.hpp
  LiteLoader/src/liteloader/BuiltinBugFix.cpp
  LiteLoader/src/liteloader/LiteLoader.rc
  LiteLoader/src/liteloader/ModifyInfomation.cpp
  LiteLoader/src/llapi/EventAPI.cpp
  LiteLoader/src/llapi/LLAPI.cpp
  LiteLoader/src/llapi/PlayerInfoAPI.cpp
  LiteLoader/src/llapi/mc/PlayerAPI.cpp
  LiteLoader/src/llapi/scoreboard/ScoreboardAPI.cpp
  ScriptEngine/src/api/DataAPI.cpp
  ScriptEngine/src/api/DataAPI.h
  ScriptEngine/src/api/EntityAPI.cpp
  ScriptEngine/src/api/EntityAPI.h
  ScriptEngine/src/api/EventAPI.cpp
  ScriptEngine/src/api/PlayerAPI.cpp
  ScriptEngine/src/api/PlayerAPI.h
  ScriptEngine/src/res/ScriptEngine.rc
Labels: type: enhancement, module: LiteLoader, priority: normal, about: CI
